# Generated by Django 2.2.17 on 2021-01-17 19:07
# python manage.py makemigrations bu işlem yapıldıktan sonra bu dosya oluştu.....
# python manage.py migrate burdaki migration dosyasına göre bizim  tablomuzu oluşturacak....
# article.0001_initial... OK bunu çalıştırdı....

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
